name: Deploy Build Folder

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies and build
        run: |
          yarn install
          yarn build

      # === YANGI STEP: SSH kalitlarni sozlash ===
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          # host ni known_hosts ga qo'shish:
          ssh-keyscan -H 143.198.198.121 >> ~/.ssh/known_hosts

      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no root@143.198.198.121 "rm -rf /var/www/arendumAdmin/*"
          scp -r build/* root@143.198.198.121:/var/www/arendumAdmin/
